### ISSUE TITLE
Deserialization Problem

### ISSUE THREAD

**Issue by dradovic** [99darshan/DotNetCoreRESTCountry#3]
When I call: 
`RestCountry.Code("AD");`

I get:

> Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[DotNetRestCountries.Country]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'name', line 1, position 8.

**Comment by elylv** [comment]
I am also getting this error.

**Comment by 99darshan** [comment]
@dradovic @elylv Thank you for notifying about the issue. This should now be resolved with the updated version `1.0.4`
